### ISSUE TITLE
Upload service first milestone

### ISSUE THREAD

**Issue by Sahl-A** [m3ntorship/pickify-upload#1]
### Story
- As a user/client, I want the ability to receive a binary media file (image), upload it to a provider,i.e. Cloudinary, then respond with the url of the uploaded file. 

### Tasks
- [ ]  add `POST /api/media` endpoint
- [ ]  add upload module with its service
- [ ]  add multer configuration
- [ ] add cloudinary module with its configuration
- [ ] add cloudinary secrets to github actions workflows 
- [ ] use cloudinary secrect as environment variables in configuration and deployment files 

### Acceptance criteria
- whenever `POST /api/media` is called with binary media file, it should be uploaded to the configured provider. For now the provider is cloudinary, then respond with the url.
